In [1]:
import numpy as np
from copy import deepcopy
import pandas as pd
#get center of cell marked
#cell size over x marked in seperate color
# put every cluster in a csv file
    
import numpy as np
import matplotlib.pyplot as plt
from scipy import ndimage as ndi
from skimage.morphology import watershed
from skimage.feature import peak_local_max
from PIL import Image
import cv2
from skimage.morphology import skeletonize, thin
from skimage.util import invert
from skimage import measure
from skimage.morphology import erosion, dilation, opening, closing, white_tophat
from skimage.morphology import black_tophat, skeletonize, convex_hull_image
from skimage.morphology import disk
from skimage import feature
from skimage.filters import roberts, sobel, scharr, prewitt
import seaborn as sns
sns.reset_orig()
from skimage import measure
from skimage import restoration

from skimage import exposure
from skimage.filters import gaussian

from scipy import ndimage

from time import time

from skimage.color import rgb2gray


from skimage.filters.rank import entropy
import scipy

from skimage import data, filters

import networkx as nx
from scipy import interpolate

from skimage.segmentation import random_walker
from skimage.data import binary_blobs
from skimage.exposure import rescale_intensity
import glob

from skimage.morphology import disk
from skimage import io

import matplotlib.colors
from skimage import data
from skimage.color import rgb2hsv

from mpl_toolkits.mplot3d import axes3d, Axes3D

/Users/spencerlab/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py:855: MatplotlibDeprecationWarning: 
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))
/Users/spencerlab/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py:846: MatplotlibDeprecationWarning: 
The text.latex.unicode rcparam was deprecated in Matplotlib 2.2 and will be removed in 3.1.
  "2.2", name=key, obj_type="rcparam", addendum=addendum)


In [ ]:
#get theymus edge also
#modify program to have bounds and a try exception for the values outside to be 0

In [2]:
#bmap = io.imread("D:/chrome download/Blood_vessel_day_3.tif")
bmap = io.imread("ined.tif")
#274
#

In [3]:
bmap = np.swapaxes(bmap,0,1)
bmap.shape

(822, 2752, 3968)

In [4]:
data1 = pd.read_csv("newgreen.csv")
data = data1.to_numpy()
data[1]
data = data[:,1:4]

data[:,0]= data[:,0]*3+1
data.shape

(578, 3)

In [5]:
data[0]

array([   7., 1420., 1837.])

In [6]:
bmap[3,1420,1837]

0

In [7]:
bmap.shape
#z y x

(822, 2752, 3968)

In [8]:
x=[[[0,0,0,1,0,1,0,0,0,0,0]]]
np.transpose(np.nonzero(x))
idx = np.argwhere(x)
f=0
y=0
z=0
idx[((idx - [z,y,f])**2).sum(1).argmin()]

array([0, 0, 3])

In [9]:
#76 and 77 arent cells
lmo = io.imread("x7.tif")
#z y x

In [10]:
for i in range(len(data)):
    try:
        if lmo[int(data[i,0]),int(data[i,1]),int(data[i,2])] ==0:
            print(i)
            data = np.delete(data,obj = i,axis=0)
    except:
        print(i)
        #np.delete(data,obj = i,axis=0)

263
530
552
569
574
575
576
577


In [11]:
i=50
len(data)


574

In [12]:
def calulate(dat, bma)
    data = data
    bmap = bma
    thing=[0,0]
    fails=[0]
    for i in range(len(data)):
        try:
            radius = 3
            array = [[[0]]]
            z_centriod= data[i,0]
            y_centriod= data[i,1]
            x_centriod= data[i,2]
            while(np.sum(array)==0):
                array = (bmap[int(z_centriod-radius):int(z_centriod+radius+1), int(y_centriod-radius):int(y_centriod+radius+1)
                          , int(x_centriod-radius):int(x_centriod+radius+1)] ).copy() 
            #set everything outside the radius to 0

                z0, y0, x0 = int(np.floor(array.shape[0]/2)), \
                int(np.floor(array.shape[1]/2)), int(np.floor(array.shape[2]/2))
                for x in range(x0-radius, x0+radius+1):
                    for y in range(y0-radius, y0+radius+1):
                        for z in range(z0-radius, z0+radius+1):   
                            deb = radius - abs(x0-x) - abs(y0-y) - abs(z0-z) 
                            if (deb)>=0: 
                                array[z,y,x] = array[z,y,x]
                            else:
                                array[z,y,x] = 0
                radius +=2
            # gives indicies of all non zero values in the sphere
            #np.transpose(np.nonzero(x))
            l = np.argwhere(array)
            m=l[((l - [z0,y0,x0])**2).sum(1).argmin()]
            dist = ((m[0]-z0)**2+(m[1]-y0)**2+((m[2]-x0))**2)**.5
            add=[i,dist]
            thing = np.vstack((thing,add))
            print(add)

        except:
            print(i + "errored")
            fails=np.vstack((fails,i))
            pass # doing nothing on exception


9
[1, 7.280109889280518]
[2, 6.4031242374328485]
[3, 3.605551275463989]
[4, 7.0710678118654755]
[5, 6.708203932499369]
[6, 7.615773105863909]
[7, 0.0]
[8, 4.0]
[9, 3.3166247903554]
[10, 0.0]
[11, 3.1622776601683795]
[12, 1.0]
[13, 0.0]
[14, 9.0]
[15, 10.0]
[16, 6.708203932499369]
[17, 3.1622776601683795]
[18, 1.4142135623730951]
[19, 3.0]
[20, 3.0]
[21, 7.810249675906654]
[22, 6.0]
[23, 12.041594578792296]
[24, 4.0]
[25, 0.0]
[26, 10.488088481701515]
[27, 2.0]
[28, 0.0]
[29, 0.0]
[30, 3.0]
[31, 17.029386365926403]
[32, 0.0]
[33, 13.038404810405298]
[34, 5.0]
[35, 3.1622776601683795]
[36, 2.23606797749979]
[37, 0.0]
[38, 3.3166247903554]
[39, 7.810249675906654]
[40, 0.0]
[41, 1.0]
[42, 2.0]
[43, 10.04987562112089]
[44, 7.681145747868608]
[45, 2.0]
[46, 2.449489742783178]
[47, 1.0]
[48, 5.0990195135927845]
[49, 0.0]
[50, 8.94427190999916]
[51, 5.0990195135927845]
[52, 3.3166247903554]
[53, 6.0]
[54, 0.0]
[55, 6.708203932499369]
[56, 6.0]
[57, 2.0]
[58, 6.0]
[59, 6.082762530298219]
[60, 0

[454, 14.422205101855956]
[455, 1.4142135623730951]
[456, 2.23606797749979]
[457, 0.0]
[458, 2.8284271247461903]
[459, 3.1622776601683795]
[460, 1.0]
[461, 3.0]
[462, 10.04987562112089]
[463, 1.0]
[464, 0.0]
[465, 0.0]
[466, 0.0]
[467, 3.3166247903554]
[468, 3.0]
[469, 3.0]
[470, 0.0]
[471, 10.198039027185569]
[472, 4.242640687119285]
[473, 0.0]
[474, 5.0]
[475, 3.0]
[476, 1.0]
[477, 0.0]
[478, 0.0]
[479, 3.0]
[480, 0.0]
[481, 5.0]
[482, 10.44030650891055]
[483, 9.1104335791443]
[484, 1.4142135623730951]
[485, 11.0]
[486, 2.0]
[487, 9.899494936611665]
[488, 0.0]
[489, 12.0]
[490, 3.605551275463989]
[491, 18.0]
[492, 5.385164807134504]
[493, 10.344080432788601]
[494, 0.0]
[495, 5.0]
[496, 3.1622776601683795]
[497, 12.96148139681572]
[498, 0.0]
[499, 5.0990195135927845]
[500, 3.1622776601683795]
[501, 0.0]
[502, 3.0]
[503, 6.082762530298219]
[504, 7.0]
[505, 5.0]
[506, 5.0]
[507, 0.0]
[508, 3.1622776601683795]
[509, 0.0]
[510, 0.0]
[511, 4.0]
[512, 0.0]
[513, 20.0]
[514, 0.0]
[515, 1.414

In [13]:
thing

array([[  0.        ,   0.        ],
       [  1.        ,   7.28010989],
       [  2.        ,   6.40312424],
       ...,
       [571.        ,   2.23606798],
       [572.        ,   0.        ],
       [573.        ,   1.        ]])

In [19]:
len(fails)

2

In [26]:
thing=np.delete(thing,obj=0,axis=0)

array([], shape=(0, 0), dtype=int64)

In [27]:
pd.DataFrame(thing).to_csv("finals.csv")