In [29]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import ndimage as ndi

from skimage.morphology import watershed
from skimage.feature import peak_local_max
from PIL import Image

from skimage.morphology import skeletonize, thin
from skimage.util import invert
from skimage import measure
from skimage.morphology import erosion, dilation, opening, closing, white_tophat
from skimage.morphology import black_tophat, skeletonize, convex_hull_image
from skimage.morphology import disk
from skimage import feature
from skimage.filters import roberts, sobel, scharr, prewitt
import seaborn as sns
sns.reset_orig()

from skimage import restoration

from skimage import exposure
from skimage.filters import gaussian

from scipy import ndimage

from time import time

from skimage.color import rgb2gray
from scipy import ndimage as ndi

from skimage.filters.rank import entropy
import scipy


import networkx as nx
from scipy import interpolate

from skimage.segmentation import random_walker
from skimage.data import binary_blobs
from skimage.exposure import rescale_intensity
import glob

from skimage.morphology import disk
from skimage import io


from skimage.external import tifffile

import pandas as pd

from sklearn.cluster import KMeans

/Users/spencerlab/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py:855: MatplotlibDeprecationWarning: 
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))
/Users/spencerlab/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py:846: MatplotlibDeprecationWarning: 
The text.latex.unicode rcparam was deprecated in Matplotlib 2.2 and will be removed in 3.1.
  "2.2", name=key, obj_type="rcparam", addendum=addendum)


In [52]:
csv = pd.read_csv('newgreen.csv')

In [53]:
data = np.asarray(csv.values).astype("int")

In [54]:
data0 = data[:,1:6]
data0[:,0] = (data0[:,0]-1)*3
data0[:,3] = data0[:,3]*3

In [55]:
data0.shape

(578, 5)

In [34]:
#bin_stack=io.imread("x7.tif")


In [35]:
#x=0
#for n in range(len(data0)):
#    print(bin_stack[data0[n,0],data0[n,1],data0[n,2]])
#    if bin_stack[data0[n,0],data0[n,1],data0[n,2]]==0: 
#        data0[n,3]= data0[n,3]*0
#        x+=1
#print(x)

In [36]:
#data1=data0[np.where(data0[:,3]!=0)]

In [56]:
data1.shape

(578, 5)

In [57]:
data1=data0

In [58]:
def col(xtif,ytif,ztif,incsv):
    x =io.imread(str(xtif))
    y =io.imread(str(ytif))
    z =io.imread(str(ztif))

    out1=[]
    out2=[]
    out3=[]
    out4=[]
    #tif = intif
    csv = incsv
    
    for n in range(len(csv)):
        value1 = z[csv[n,0],csv[n,1],csv[n,2]]
        value2 = x[csv[n,0],csv[n,1],csv[n,2]]
        value3 = y[csv[n,0],csv[n,1],csv[n,2]]
        out1.append(value1)
        out2.append(value2)    
        out3.append(value3)
        value4= ((value1-csv[n,0])**2+(value2-csv[n,1])**2+(value3-csv[n,2])**2)**.5
        out4.append(value4)
    
    csv= np.column_stack((csv,out1))
    csv= np.column_stack((csv,out2))
    csv= np.column_stack((csv,out3))
    csv= np.column_stack((csv,out4))

    #for n in range(len(csv)):
    #    value4= ((out1[n]-csv[n,0])^2+(out2[n]-csv[n,1])^2+(out3[n]-csv[n,2])^2)^.5
     #   out4.append(value4)
    
    #csv = np.append(csv,out4)

    return csv

In [2]:
2**0.5

1.4142135623730951

In [59]:
#xblood yblood,zblood


In [60]:
data2= col("dis_x_2.tif","dis_y_2.tif","dis_z_2.tif",data1)

In [61]:
data2

array([[   3.        , 1420.        , 1837.        , ..., 1831.        ,
        1418.        ,  586.92929728],
       [   6.        , 1415.        , 1850.        , ..., 1852.        ,
        1415.        ,  616.62792671],
       [   9.        , 1499.        , 1845.        , ..., 1840.        ,
        1499.        ,  485.80448742],
       ...,
       [ 543.        ,  902.        ,  769.        , ...,  772.        ,
         901.        ,  185.26737435],
       [ 540.        , 1151.        , 1342.        , ..., 1342.        ,
        1151.        ,  270.11479041],
       [ 585.        , 1305.        ,  799.        , ...,  798.        ,
        1306.        ,  717.00697347]])

In [62]:
data3= col("dis_x_t.tif","dis_y_t.tif","dis_z_t.tif",data1)

In [63]:
data3[1]

array([   6.        , 1415.        , 1850.        ,  273.        ,
          2.        ,    0.        , 1810.        , 1321.        ,
        660.22874824])

In [64]:
data4= np.column_stack((data2,data3[:,5:]))



In [65]:
data4.shape

(578, 13)

In [66]:
data4[1]


array([   6.        , 1415.        , 1850.        ,  273.        ,
          2.        ,    0.        , 1852.        , 1415.        ,
        616.62792671,    0.        , 1810.        , 1321.        ,
        660.22874824])

In [67]:
df = pd.DataFrame(data4, columns= ['Z', 'Y', 'X', 'size','measure','Zb', 'Yb', 'Xb', 'distb','Zt', 'Yt', 'Xt', 'distT'])

In [68]:
df.to_csv('all2.csv')

In [241]:
out1=[1,1,1,1,1]
out2=[2,2,2,2,2]
out3=[3,3,3,3,3]
out4=[4,4,4,4,4]

csv2= []

In [242]:
csv =np.column_stack((csv,out1))
csv =np.column_stack((csv,out2))
csv =np.column_stack((csv,out2))


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [ ]:
csv

In [ ]:
n=1
value3= ((out1[n]-csv[n,0])**2+(out2[n]-csv[n,1])**2+(out3[n]-csv[n,2])**2)**.5
value3